name: PlaceholderInjector
main: me.clip.placeholderinjector.PlaceholderInjector
version: 1.5
author: [extended_clip, GGhost]
description: Inject PlaceholderAPI placeholders into everything!
softdepend: [ProtocolLib, PlaceholderAPI, HolographicDisplays]
permissions:
    placeholderinjector.chat.bypass:
        description: ability to use placeholders in chat messages
        default: op
    placeholderinjector.signs.bypass:
        description: ability to use placeholders in signs
        default: op